from setuptools import setup

setup(
    name='wavy',
    version='0.0.1',
    packages=['test', 'test.unit_tests', 'test.unit_tests.detail', 'test.integration',
              'venv.lib.python3.6.site-packages.py', 'venv.lib.python3.6.site-packages.py._io',
              'venv.lib.python3.6.site-packages.py._log', 'venv.lib.python3.6.site-packages.py._code',
              'venv.lib.python3.6.site-packages.py._path', 'venv.lib.python3.6.site-packages.py._process',
              'venv.lib.python3.6.site-packages.py._vendored_packages', 'venv.lib.python3.6.site-packages.attr',
              'venv.lib.python3.6.site-packages.numpy', 'venv.lib.python3.6.site-packages.numpy.ma',
              'venv.lib.python3.6.site-packages.numpy.ma.tests', 'venv.lib.python3.6.site-packages.numpy.doc',
              'venv.lib.python3.6.site-packages.numpy.fft', 'venv.lib.python3.6.site-packages.numpy.fft.tests',
              'venv.lib.python3.6.site-packages.numpy.lib', 'venv.lib.python3.6.site-packages.numpy.lib.tests',
              'venv.lib.python3.6.site-packages.numpy.core', 'venv.lib.python3.6.site-packages.numpy.core.tests',
              'venv.lib.python3.6.site-packages.numpy.f2py', 'venv.lib.python3.6.site-packages.numpy.f2py.tests',
              'venv.lib.python3.6.site-packages.numpy.tests', 'venv.lib.python3.6.site-packages.numpy.compat',
              'venv.lib.python3.6.site-packages.numpy.linalg', 'venv.lib.python3.6.site-packages.numpy.linalg.tests',
              'venv.lib.python3.6.site-packages.numpy.random', 'venv.lib.python3.6.site-packages.numpy.random.tests',
              'venv.lib.python3.6.site-packages.numpy.testing', 'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing.nose_tools',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.scipy',
              'venv.lib.python3.6.site-packages.scipy.io', 'venv.lib.python3.6.site-packages.scipy.io.arff',
              'venv.lib.python3.6.site-packages.scipy.io.arff.tests', 'venv.lib.python3.6.site-packages.scipy.io.tests',
              'venv.lib.python3.6.site-packages.scipy.io.matlab',
              'venv.lib.python3.6.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.6.site-packages.scipy.odr', 'venv.lib.python3.6.site-packages.scipy.odr.tests',
              'venv.lib.python3.6.site-packages.scipy._lib', 'venv.lib.python3.6.site-packages.scipy._lib.tests',
              'venv.lib.python3.6.site-packages.scipy.misc', 'venv.lib.python3.6.site-packages.scipy.misc.tests',
              'venv.lib.python3.6.site-packages.scipy.stats', 'venv.lib.python3.6.site-packages.scipy.stats.tests',
              'venv.lib.python3.6.site-packages.scipy.linalg', 'venv.lib.python3.6.site-packages.scipy.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.signal', 'venv.lib.python3.6.site-packages.scipy.signal.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse', 'venv.lib.python3.6.site-packages.scipy.sparse.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.6.site-packages.scipy.cluster', 'venv.lib.python3.6.site-packages.scipy.cluster.tests',
              'venv.lib.python3.6.site-packages.scipy.fftpack', 'venv.lib.python3.6.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.6.site-packages.scipy.ndimage', 'venv.lib.python3.6.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.6.site-packages.scipy.spatial', 'venv.lib.python3.6.site-packages.scipy.spatial.tests',
              'venv.lib.python3.6.site-packages.scipy.special', 'venv.lib.python3.6.site-packages.scipy.special.tests',
              'venv.lib.python3.6.site-packages.scipy.special._precompute',
              'venv.lib.python3.6.site-packages.scipy.optimize', 'venv.lib.python3.6.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.6.site-packages.scipy.optimize.tests',
              'venv.lib.python3.6.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.6.site-packages.scipy.constants',
              'venv.lib.python3.6.site-packages.scipy.constants.tests',
              'venv.lib.python3.6.site-packages.scipy.integrate',
              'venv.lib.python3.6.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.6.site-packages.scipy.integrate.tests',
              'venv.lib.python3.6.site-packages.scipy.interpolate',
              'venv.lib.python3.6.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.6.site-packages.scipy._build_utils', 'venv.lib.python3.6.site-packages.pluggy',
              'venv.lib.python3.6.site-packages._pytest', 'venv.lib.python3.6.site-packages._pytest._code',
              'venv.lib.python3.6.site-packages._pytest.assertion',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.operations', 'wavy', 'wavy.detail'],
    url='https://github.com/acelletti/wavy',
    license='MIT',
    author='Andrea Celletti',
    author_email='celletti.andrea87@gmail.com',
    description='A module to read and write WAVE files.'
)
